import Head from 'next/head';

import { ChildProps } from '~/types/ChildProps';
import { Footer } from '~/ui/.';

const MainLayout = ({ children }: ChildProps) => {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Testimonials grid section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className="flex flex-col justify-between h-full xl:h-screen">
        {children}
      </main>
      <Footer />
    </>
  );
};

export { MainLayout };
